#!/bin/lua

--===== conf =====--
local execResultFile = "/tmp/.ibcExecutionResults"

--===== vars =====--
--runtime vars
local args = ""
local lastResult

-- aliases
local len = require("utf8").len

--===== functions =====--
local function exec(command)
	print("exec:", command)
	--os.execute(command .. ">")
end

--===== init =====--
for _, v in ipairs({...}) do
	args = args .. tostring(v)
end

do --check if execResult file already exists, to prevent unwantet overwriting
	local file = io.open(execResultFile, "r")
	if file ~= nil then
		print("execResultFile (" .. execResultFile .. ") already exitst. Please delete it manually before running the interactive bc ")
	end	
end

--===== program start =====--
if len(args) > 0 then --non interactive mode
	exec("echo " .. args .. " | bc")
	os.exit(0)
else --interactive mode

end